name = "second-brain-sync"
main = "worker.js"
compatibility_date = "2024-12-01"

[vars]
CORS_ORIGIN = "https://osthainthale21.github.io"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "044699742bf54f97ae8c5ccf5faa93f5"

[[d1_databases]]
binding = "USERS_DB"
database_name = "secondbrain_users"
database_id = "e6fad1f2-865b-4f94-821e-df2b2e850723"
